### PR TITLE
Added Dockerfile for container image version

### PR DESCRIPTION
**Pull request by UnoSD**

### CODE REVIEW

**Comment by aslafy-z** [comment]
I vote for keeping the Dockerfile directly in this repo.

**Comment by tracker1** [comment]
Agreed with aslafy-z, the dockerfile really should be *in* this repo, as without it I doubt anyone would even look for it.

**Comment by UnoSD** [comment]
I'm happy either way, but I haven't had any feedback from @niftylettuce, maybe he did not get a chance to look at the file.

**Comment by dapetcu21** [comment]
Hi! I made some improvements to your Dockerfile in #170

**Comment by niftylettuce** [comment]
Closed per #170

**Pull request closed without merging**
